### ISSUE TITLE
isRedLightOn bug

### ISSUE THREAD

**Issue by jayanthkaturi** [bondib/kibana-traffic-light-vis-plugin#1]
metricValue in [here](https://github.com/bondib/kibana-traffic-light-vis-plugin/blob/master/public/traffic_light_vis_controller.js#L18) is accessed as metricValue.value, it shoud be just mericValue right? (In the second part of condition  `node  (params.invertScale && metricValue.value >= params.redThreshold` )

``` nodejs
isRedLightOn: (!params.invertScale && metricValue <= params.redThreshold) || (params.invertScale && metricValue.value >= params.redThreshold)
```

**Comment by joydragon** [comment]
Yeah, that solved the issue for me as well
Thanks!

**Comment by bondib** [comment]
Thanks for the input - it's now fixed.
